const mongoose = require("mongoose");
const job = require("./models/Jobs");
const dotenv = require("dotenv");

dotenv.config();

const MONGO_URI = process.env.MONGODB_URI;

const jobs = [
  {
    title: "Frontend Developer",
    company: "Tech Solutions Inc.",
    location: "New York, USA",
    skills: ["JavaScript", "React", "CSS", "HTML"],
    jobType: "Remote",
    description: "Develop and maintain web applications with React.",
    salary: 85000,
    experienceInYears: 2,
    postedAt: "2025-05-01T10:00:00Z",
  },
  {
    title: "Backend Engineer",
    company: "CloudNet",
    location: "San Francisco, USA",
    skills: ["Node.js", "Express", "MongoDB", "REST API"],
    jobType: "Hybrid",
    description: "Build scalable backend services and APIs.",
    salary: 95000,
    experienceInYears: 3,
    postedAt: "2025-05-03T09:30:00Z",
  },
  {
    title: "Full Stack Developer",
    company: "Innovatech",
    location: "Austin, USA",
    skills: ["React", "Node.js", "GraphQL", "TypeScript"],
    jobType: "Onsite",
    description: "Work on both frontend and backend to deliver full projects.",
    salary: 105000,
    experienceInYears: 4,
    postedAt: "2025-05-04T08:00:00Z",
  },
  {
    title: "Data Scientist",
    company: "DataMine Corp.",
    location: "Boston, USA",
    skills: ["Python", "Machine Learning", "TensorFlow", "Pandas"],
    jobType: "Remote",
    description: "Analyze large datasets and build predictive models.",
    salary: 120000,
    experienceInYears: 3,
    postedAt: "2025-04-28T11:00:00Z",
  },
  {
    title: "Mobile App Developer",
    company: "AppWorks",
    location: "Seattle, USA",
    skills: ["Flutter", "Dart", "Firebase"],
    jobType: "Hybrid",
    description: "Develop cross-platform mobile applications.",
    salary: 90000,
    experienceInYears: 2,
    postedAt: "2025-05-05T13:45:00Z",
  },
  {
    title: "DevOps Engineer",
    company: "CloudOps",
    location: "Denver, USA",
    skills: ["AWS", "Docker", "Kubernetes", "CI/CD"],
    jobType: "Onsite",
    description: "Manage infrastructure and automate deployments.",
    salary: 110000,
    experienceInYears: 4,
    postedAt: "2025-05-02T12:00:00Z",
  },
  {
    title: "UX/UI Designer",
    company: "DesignPro",
    location: "Chicago, USA",
    skills: ["Figma", "Adobe XD", "User Research"],
    jobType: "Remote",
    description: "Design user-friendly interfaces and experiences.",
    salary: 75000,
    experienceInYears: 2,
    postedAt: "2025-05-06T09:00:00Z",
  },
  {
    title: "Quality Assurance Engineer",
    company: "SoftTest Labs",
    location: "Atlanta, USA",
    skills: ["Selenium", "Jest", "Manual Testing"],
    jobType: "Hybrid",
    description: "Test software applications for bugs and performance.",
    salary: 70000,
    experienceInYears: 1,
    postedAt: "2025-05-07T14:30:00Z",
  },
  {
    title: "Product Manager",
    company: "NextGen Products",
    location: "New York, USA",
    skills: ["Agile", "Scrum", "Roadmap Planning"],
    jobType: "Onsite",
    description: "Lead product development and coordinate teams.",
    salary: 115000,
    experienceInYears: 5,
    postedAt: "2025-05-01T15:00:00Z",
  },
  {
    title: "Cloud Architect",
    company: "SkyTech",
    location: "San Jose, USA",
    skills: ["AWS", "Azure", "GCP", "Terraform"],
    jobType: "Remote",
    description: "Design cloud infrastructure for scalable solutions.",
    salary: 130000,
    experienceInYears: 6,
    postedAt: "2025-05-03T10:30:00Z",
  },
  {
    title: "Software Engineer",
    company: "Alpha Systems",
    location: "Dallas, USA",
    skills: ["Java", "Spring Boot", "Microservices"],
    jobType: "Hybrid",
    description: "Develop microservices and backend components.",
    salary: 90000,
    experienceInYears: 3,
    postedAt: "2025-05-04T16:00:00Z",
  },
  {
    title: "Cybersecurity Analyst",
    company: "SecureNet",
    location: "Washington, D.C., USA",
    skills: ["Network Security", "Penetration Testing", "Firewalls"],
    jobType: "Onsite",
    description: "Monitor and secure enterprise systems.",
    salary: 95000,
    experienceInYears: 4,
    postedAt: "2025-05-02T08:45:00Z",
  },
  {
    title: "Machine Learning Engineer",
    company: "AI Innovators",
    location: "Palo Alto, USA",
    skills: ["Python", "PyTorch", "TensorFlow", "Data Analysis"],
    jobType: "Remote",
    description: "Develop and optimize ML models.",
    salary: 125000,
    experienceInYears: 5,
    postedAt: "2025-05-06T11:15:00Z",
  },
  {
    title: "Technical Support Specialist",
    company: "HelpDesk Co.",
    location: "Orlando, USA",
    skills: ["Customer Service", "Troubleshooting", "Windows"],
    jobType: "Hybrid",
    description: "Assist customers with technical issues.",
    salary: 50000,
    experienceInYears: 1,
    postedAt: "2025-05-07T09:00:00Z",
  },
  {
    title: "Database Administrator",
    company: "DataGuard",
    location: "Houston, USA",
    skills: ["SQL", "MongoDB", "Performance Tuning"],
    jobType: "Onsite",
    description: "Manage and optimize databases.",
    salary: 85000,
    experienceInYears: 4,
    postedAt: "2025-05-01T10:00:00Z",
  },
  {
    title: "DevSecOps Engineer",
    company: "SecureCloud",
    location: "Remote",
    skills: ["AWS", "Docker", "Kubernetes", "Security"],
    jobType: "Remote",
    description: "Integrate security in DevOps pipelines.",
    salary: 115000,
    experienceInYears: 5,
    postedAt: "2025-05-03T12:00:00Z",
  },
  {
    title: "Business Analyst",
    company: "BizInsights",
    location: "Philadelphia, USA",
    skills: ["Data Analysis", "SQL", "Communication"],
    jobType: "Hybrid",
    description: "Analyze business needs and deliver solutions.",
    salary: 78000,
    experienceInYears: 3,
    postedAt: "2025-05-04T14:30:00Z",
  },
  {
    title: "Software Architect",
    company: "Tech Architects",
    location: "San Diego, USA",
    skills: ["System Design", "Microservices", "Java"],
    jobType: "Onsite",
    description: "Design software systems and mentor engineers.",
    salary: 140000,
    experienceInYears: 7,
    postedAt: "2025-05-05T09:00:00Z",
  },
  {
    title: "Network Engineer",
    company: "NetSecure",
    location: "Miami, USA",
    skills: ["Cisco", "Routing", "Switching"],
    jobType: "Remote",
    description: "Maintain and optimize network infrastructure.",
    salary: 90000,
    experienceInYears: 4,
    postedAt: "2025-05-06T10:30:00Z",
  },
  {
    title: "Frontend Engineer",
    company: "WebWorks",
    location: "Portland, USA",
    skills: ["Vue.js", "JavaScript", "CSS"],
    jobType: "Hybrid",
    description: "Build responsive UI components.",
    salary: 80000,
    experienceInYears: 2,
    postedAt: "2025-05-07T11:00:00Z",
  },
  {
    title: "AI Research Scientist",
    company: "DeepThink Labs",
    location: "Cambridge, USA",
    skills: ["Python", "Deep Learning", "PyTorch"],
    jobType: "Onsite",
    description: "Conduct cutting-edge AI research.",
    salary: 150000,
    experienceInYears: 6,
    postedAt: "2025-05-01T08:00:00Z",
  },
  {
    title: "Technical Writer",
    company: "DocuWrite",
    location: "Remote",
    skills: ["Writing", "Markdown", "API Documentation"],
    jobType: "Remote",
    description: "Create and maintain technical documentation.",
    salary: 65000,
    experienceInYears: 2,
    postedAt: "2025-05-03T15:00:00Z",
  },
  {
    title: "QA Automation Engineer",
    company: "TestPro",
    location: "Salt Lake City, USA",
    skills: ["Selenium", "JavaScript", "Cypress"],
    jobType: "Hybrid",
    description: "Develop automated test scripts.",
    salary: 85000,
    experienceInYears: 3,
    postedAt: "2025-05-04T12:00:00Z",
  },
  {
    title: "Product Owner",
    company: "AgileWorks",
    location: "New York, USA",
    skills: ["Scrum", "Agile", "Backlog Management"],
    jobType: "Onsite",
    description: "Manage product backlog and priorities.",
    salary: 110000,
    experienceInYears: 4,
    postedAt: "2025-05-05T14:00:00Z",
  },
  {
    title: "Game Developer",
    company: "FunGames",
    location: "Los Angeles, USA",
    skills: ["Unity", "C#", "3D Modeling"],
    jobType: "Remote",
    description: "Develop immersive game experiences.",
    salary: 95000,
    experienceInYears: 3,
    postedAt: "2025-05-06T13:00:00Z",
  },
  {
    title: "System Administrator",
    company: "SysAdmin Corp",
    location: "Houston, USA",
    skills: ["Linux", "Windows Server", "Shell Scripting"],
    jobType: "Hybrid",
    description: "Maintain servers and system infrastructure.",
    salary: 78000,
    experienceInYears: 4,
    postedAt: "2025-05-07T10:30:00Z",
  },
  {
    title: "Mobile QA Tester",
    company: "AppTesters",
    location: "Chicago, USA",
    skills: ["Manual Testing", "Bug Reporting"],
    jobType: "Onsite",
    description: "Test mobile apps and report issues.",
    salary: 60000,
    experienceInYears: 1,
    postedAt: "2025-05-01T09:00:00Z",
  },
  {
    title: "Cloud Engineer",
    company: "CloudWorks",
    location: "Seattle, USA",
    skills: ["AWS", "Azure", "Terraform"],
    jobType: "Remote",
    description: "Design and maintain cloud infrastructure.",
    salary: 115000,
    experienceInYears: 4,
    postedAt: "2025-05-03T11:30:00Z",
  },
  {
    title: "Blockchain Developer",
    company: "CryptoTech",
    location: "San Francisco, USA",
    skills: ["Solidity", "Ethereum", "Smart Contracts"],
    jobType: "Hybrid",
    description: "Develop blockchain-based applications.",
    salary: 130000,
    experienceInYears: 5,
    postedAt: "2025-05-04T14:00:00Z",
  },
  {
    title: "IT Support Engineer",
    company: "TechHelp",
    location: "Miami, USA",
    skills: ["Helpdesk", "Windows", "Troubleshooting"],
    jobType: "Onsite",
    description: "Provide IT support for internal users.",
    salary: 55000,
    experienceInYears: 1,
    postedAt: "2025-05-05T08:30:00Z",
  },
  {
    title: "Software Tester",
    company: "QA Masters",
    location: "Boston, USA",
    skills: ["Manual Testing", "Test Cases", "Bug Tracking"],
    jobType: "Remote",
    description: "Test software for defects and usability.",
    salary: 65000,
    experienceInYears: 2,
    postedAt: "2025-05-06T09:45:00Z",
  },
  {
    title: "Technical Project Manager",
    company: "Projex",
    location: "Austin, USA",
    skills: ["Project Management", "Agile", "JIRA"],
    jobType: "Hybrid",
    description: "Manage software development projects.",
    salary: 120000,
    experienceInYears: 6,
    postedAt: "2025-05-07T13:00:00Z",
  },
  {
    title: "Digital Marketing Specialist",
    company: "MarketPros",
    location: "Los Angeles, USA",
    skills: ["SEO", "Google Ads", "Content Marketing"],
    jobType: "Remote",
    description: "Plan and execute digital marketing campaigns.",
    salary: 70000,
    experienceInYears: 3,
    postedAt: "2025-05-01T10:30:00Z",
  },
  {
    title: "Embedded Systems Engineer",
    company: "EmbedTech",
    location: "San Diego, USA",
    skills: ["C", "C++", "RTOS"],
    jobType: "Onsite",
    description: "Develop firmware for embedded devices.",
    salary: 95000,
    experienceInYears: 4,
    postedAt: "2025-05-03T09:15:00Z",
  },
  {
    title: "Systems Analyst",
    company: "SysAnalyze",
    location: "Denver, USA",
    skills: ["Requirement Gathering", "UML", "SQL"],
    jobType: "Hybrid",
    description: "Analyze and improve IT systems.",
    salary: 85000,
    experienceInYears: 3,
    postedAt: "2025-05-04T11:00:00Z",
  },
  {
    title: "AI Engineer",
    company: "SmartAI",
    location: "Palo Alto, USA",
    skills: ["Python", "Machine Learning", "NLP"],
    jobType: "Remote",
    description: "Build AI-driven applications.",
    salary: 130000,
    experienceInYears: 5,
    postedAt: "2025-05-05T12:45:00Z",
  },
  {
    title: "Software Consultant",
    company: "ConsultCorp",
    location: "New York, USA",
    skills: ["Java", "Spring", "Cloud"],
    jobType: "Onsite",
    description: "Advise clients on software solutions.",
    salary: 115000,
    experienceInYears: 6,
    postedAt: "2025-05-06T10:30:00Z",
  },
  {
    title: "Infrastructure Engineer",
    company: "InfraTech",
    location: "Seattle, USA",
    skills: ["Linux", "AWS", "Networking"],
    jobType: "Hybrid",
    description: "Maintain and improve IT infrastructure.",
    salary: 95000,
    experienceInYears: 4,
    postedAt: "2025-05-07T09:00:00Z",
  },
  {
    title: "Content Strategist",
    company: "Creative Minds",
    location: "Remote",
    skills: ["Content Writing", "SEO", "Social Media"],
    jobType: "Remote",
    description: "Create and manage content strategies.",
    salary: 65000,
    experienceInYears: 3,
    postedAt: "2025-05-01T08:00:00Z",
  },
  {
    title: "API Developer",
    company: "Connectify",
    location: "Denver, USA",
    skills: ["Node.js", "REST API", "Express", "Postman"],
    jobType: "Remote",
    description: "Develop and maintain scalable APIs for multiple platforms.",
    salary: 90000,
    experienceInYears: 3,
    postedAt: "2025-05-08T10:00:00Z",
  },
  {
    title: "Scrum Master",
    company: "AgileForce",
    location: "Boston, USA",
    skills: ["Scrum", "Agile", "Team Facilitation"],
    jobType: "Hybrid",
    description: "Lead agile teams and facilitate scrum ceremonies.",
    salary: 95000,
    experienceInYears: 4,
    postedAt: "2025-05-08T11:15:00Z",
  },
  {
    title: "Site Reliability Engineer",
    company: "Reliant Tech",
    location: "San Francisco, USA",
    skills: ["Kubernetes", "Docker", "Linux", "Monitoring"],
    jobType: "Onsite",
    description: "Ensure system reliability and scalability.",
    salary: 120000,
    experienceInYears: 5,
    postedAt: "2025-05-08T12:30:00Z",
  },
  {
    title: "Mobile Backend Developer",
    company: "AppCore",
    location: "Austin, USA",
    skills: ["Node.js", "Express", "Firebase", "MongoDB"],
    jobType: "Remote",
    description: "Develop backend services supporting mobile apps.",
    salary: 95000,
    experienceInYears: 3,
    postedAt: "2025-05-08T13:45:00Z",
  },
  {
    title: "Technical Recruiter",
    company: "TalentFinders",
    location: "New York, USA",
    skills: ["Recruitment", "Interviewing", "ATS", "Communication"],
    jobType: "Hybrid",
    description: "Source and hire top technical talent.",
    salary: 70000,
    experienceInYears: 2,
    postedAt: "2025-05-08T14:00:00Z",
  },
  {
    title: "Cloud Security Engineer",
    company: "SecureCloud",
    location: "Seattle, USA",
    skills: ["AWS", "Azure", "Security Policies", "Encryption"],
    jobType: "Remote",
    description: "Implement security best practices in cloud environments.",
    salary: 125000,
    experienceInYears: 5,
    postedAt: "2025-05-08T15:30:00Z",
  },
  {
    title: "Business Intelligence Analyst",
    company: "DataSense",
    location: "Chicago, USA",
    skills: ["SQL", "Power BI", "Tableau", "Data Visualization"],
    jobType: "Onsite",
    description: "Analyze data to provide actionable business insights.",
    salary: 85000,
    experienceInYears: 3,
    postedAt: "2025-05-08T16:45:00Z",
  },
  {
    title: "Embedded Software Developer",
    company: "AutoTech",
    location: "Detroit, USA",
    skills: ["C", "C++", "RTOS", "Embedded Linux"],
    jobType: "Hybrid",
    description: "Develop embedded software for automotive systems.",
    salary: 98000,
    experienceInYears: 4,
    postedAt: "2025-05-08T17:30:00Z",
  },
  {
    title: "Digital Product Designer",
    company: "PixelCraft",
    location: "Portland, USA",
    skills: ["Sketch", "Figma", "Prototyping", "User Testing"],
    jobType: "Remote",
    description: "Create user-centered designs for digital products.",
    salary: 80000,
    experienceInYears: 3,
    postedAt: "2025-05-08T18:15:00Z",
  },
  {
    title: "Solutions Architect",
    company: "Enterprise Solutions",
    location: "Atlanta, USA",
    skills: ["Cloud Architecture", "Microservices", "AWS", "Azure"],
    jobType: "Onsite",
    description: "Design complex IT solutions for enterprise clients.",
    salary: 140000,
    experienceInYears: 7,
    postedAt: "2025-05-08T19:00:00Z",
  },
  {
    title: "AI Data Engineer",
    company: "NeuroData",
    location: "Palo Alto, USA",
    skills: ["Python", "Big Data", "Spark", "Machine Learning Pipelines"],
    jobType: "Remote",
    description: "Build data pipelines to support AI model training.",
    salary: 125000,
    experienceInYears: 4,
    postedAt: "2025-05-08T20:00:00Z",
  },
  {
    title: "Frontend Developer",
    company: "BrightApps",
    location: "Miami, USA",
    skills: ["React", "JavaScript", "CSS", "TypeScript"],
    jobType: "Hybrid",
    description: "Develop interactive web interfaces for clients.",
    salary: 85000,
    experienceInYears: 2,
    postedAt: "2025-05-08T21:00:00Z",
  },
  {
    title: "Software Development Manager",
    company: "CodeMasters",
    location: "San Diego, USA",
    skills: ["Leadership", "Agile", "Java", "Project Management"],
    jobType: "Onsite",
    description: "Manage development teams and projects end-to-end.",
    salary: 135000,
    experienceInYears: 8,
    postedAt: "2025-05-08T22:00:00Z",
  },
  {
    title: "QA Lead",
    company: "TestCraft",
    location: "Salt Lake City, USA",
    skills: ["Test Automation", "Selenium", "JIRA", "Team Management"],
    jobType: "Hybrid",
    description: "Lead QA team in delivering quality software.",
    salary: 95000,
    experienceInYears: 5,
    postedAt: "2025-05-09T08:30:00Z",
  },
  {
    title: "Data Engineer",
    company: "DataWorks",
    location: "New York, USA",
    skills: ["Python", "SQL", "ETL", "Big Data"],
    jobType: "Remote",
    description: "Build and maintain scalable data infrastructure.",
    salary: 110000,
    experienceInYears: 4,
    postedAt: "2025-05-09T09:45:00Z",
  },
  {
    title: "Mobile UX Designer",
    company: "AppDesign",
    location: "Austin, USA",
    skills: ["UX Research", "Wireframing", "Figma", "Prototyping"],
    jobType: "Remote",
    description: "Design mobile-first user experiences.",
    salary: 78000,
    experienceInYears: 3,
    postedAt: "2025-05-09T10:30:00Z",
  },
  {
    title: "Cloud Infrastructure Engineer",
    company: "InfraCloud",
    location: "Seattle, USA",
    skills: ["AWS", "Terraform", "Linux", "Networking"],
    jobType: "Hybrid",
    description: "Implement and maintain cloud infrastructure.",
    salary: 115000,
    experienceInYears: 5,
    postedAt: "2025-05-09T11:15:00Z",
  },
  {
    title: "Technical Account Manager",
    company: "ClientFirst",
    location: "Philadelphia, USA",
    skills: ["Customer Success", "Technical Support", "Communication"],
    jobType: "Onsite",
    description: "Manage key client relationships and technical delivery.",
    salary: 105000,
    experienceInYears: 5,
    postedAt: "2025-05-09T12:00:00Z",
  },
  {
    title: "IT Auditor",
    company: "AuditTech",
    location: "Chicago, USA",
    skills: ["Risk Assessment", "Compliance", "Networking"],
    jobType: "Hybrid",
    description: "Conduct IT audits and ensure regulatory compliance.",
    salary: 85000,
    experienceInYears: 4,
    postedAt: "2025-05-09T13:00:00Z",
  },
  {
    title: "Robotics Engineer",
    company: "RoboWorks",
    location: "San Jose, USA",
    skills: ["C++", "ROS", "Embedded Systems"],
    jobType: "Onsite",
    description: "Develop software for robotic systems.",
    salary: 115000,
    experienceInYears: 5,
    postedAt: "2025-05-09T14:00:00Z",
  },
  {
    title: "Data Privacy Officer",
    company: "PrivacyGuard",
    location: "Washington, D.C., USA",
    skills: ["GDPR", "Data Security", "Compliance"],
    jobType: "Remote",
    description: "Ensure company compliance with data privacy laws.",
    salary: 120000,
    experienceInYears: 6,
    postedAt: "2025-05-09T15:00:00Z",
  },
  {
    title: "Front-End Engineer",
    company: "NextWave",
    location: "Los Angeles, USA",
    skills: ["Angular", "TypeScript", "CSS"],
    jobType: "Hybrid",
    description: "Develop and optimize front-end applications.",
    salary: 90000,
    experienceInYears: 3,
    postedAt: "2025-05-09T16:00:00Z",
  },
];

const seedJobs = async () => {
  try {
    await mongoose.connect(MONGO_URI);
    await job.deleteMany();
    await job.insertMany(jobs);
    console.log("Jobs seeded successfully");
  } catch (error) {
    console.error("Error seeding jobs:", error);
  } finally {
    await mongoose.disconnect();
  }
};

seedJobs();